type DeviceFrameProps = {
  src: string;
  alt: string;
  className?: string;
  eager?: boolean;
};

export function DeviceFrame({ src, alt, className = '', eager = false }: DeviceFrameProps) {
  return (
    <figure className={`device ${className}`}>
      <div className="device__speaker" aria-hidden="true" />
      {/* Real screenshots are generated by the repository capture pipeline. */}
      <Image src={src} alt={alt} width={1080} height={2400} priority={eager} sizes="(max-width: 767px) 84vw, (max-width: 1180px) 44vw, 28vw" />
    </figure>
  );
}
import Image from 'next/image';
